analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.344594
  lightness: 0.496621
  rhythmicContrast: 0.377252
  saturation: 0.533783
cta: {}
layout_spectrum: 0.49811382428742945
name: Raghav
opengraph: {}
purpose: []
typography_spectrum: 0.19355441280640662
