name: Raghav
favicon: null
layout_spectrum: 0.3636
typography_spectrum: 0.49579
title: Raghav
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71299976-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffb200'
    - '#ffaa00'
    - '#ff9900'
    - '#ff8000'
    - '#ffff00'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
