name: Raghav
favicon: null
layout_spectrum: 0.01852
typography_spectrum: 0.49579
title: Raghav
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71299976-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffb200'
    - '#ffaa00'
    - '#ff9900'
    - '#ff8000'
    - '#ffff00'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
