name: Raghav
favicon: null
layout_spectrum: 0.49811382428742945
typography_spectrum: 0.19355441280640662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffb200'
    - '#ffaa00'
    - '#ff9900'
    - '#ff8000'
    - '#ffff00'
  brandStrength: 0.25
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
